### PR TITLE
code

### PR DESCRIPTION
**Pull request by ellell**
Review: @kesla @iefserge 
Type: Major

### CODE REVIEW

**Comment by iefserge** [comment]
@ellell Looks great!
One thing, makes sense to add attributes description and values format to readme?

**Comment by kesla** [comment]
@ellell Perhaps we should compile from es6 to es5 as a pre-publish step so that this will work in nodejs?

**Comment by kesla** [comment]
But also agreed, this is great!

**Comment by ellell** [comment]
@iefserge I've updated the readme with some descriptions, does it make sense? I tried to explain it without going into too much detail of how pure.css works.

**Comment by iefserge** [comment]
Awesome, thanks!

**Pull request merged**
